### PR TITLE
Added crude hotkey rebinding system + WASAPI code cleanup

### PR DESCRIPTION
**Pull request by Shadowdevo**
I say crude because only 47 possible keys are available. No shift/ctrl modifiers or special keys (like function keys, arrow keys, esc, etc). Cleaned up a lot of the WASAPI code that went unused previously. Other than allowing more hotkeys, the only other thing I'd want to implement is the faster closing of hoot shuffle.exe and the AHK script when hoot.exe is closed. 

Currently, the AHK script will close hoot shuffle.exe and itself when hoot.exe is closed, but only if the manual shuffle button is pressed when hoot.exe is closed or when the sleep timer runs out and detects that hoot.exe had been closed. I believe there is a way to interrupt sleeps or have intervals that check conditions during sleeps in AHK but I will have to look into it.

### CODE REVIEW

**Comment by czarek7711** [comment]
Two things I've noticed while trying out the shuffling from previous pull:
1. When I shuffle manually, sometimes the next song is picked, it plays for a few seconds and then a new song is picked.
2. Sometimes the next picked stutters for half a second before playing right.

Are you experiencing similar issues?

**Comment by Shadowdevo** [comment]
> Two things I've noticed while trying out the shuffling from previous pull:

By previous pull do you mean the first one I did? Or the newest one?

> 1. When I shuffle manually, sometimes the next song is picked, it plays for a few seconds and then a new song is picked.

This will happen if you press the manual shuffle button more than once. The listening program begins counting to 5 as soon as it detects no sound or identically repeated sound. When it reaches the threshold for pressing the shuffle button itself, it will press it. So if you press the shuffle button yourself like 2-3 times or more before letting a track play first, the program just hears silence while you're shuffling and will press the shuffle key when it reaches 5 seconds of silence. I could look into resetting the variable it increments when it detects silence when you press the hotkey yourself. I think that would require some sort of keyboard event listener which might freak some people out since that could be used for keylogger stuff if done maliciously.

> 2. Sometimes the next picked stutters for half a second before playing right.

That might be an issue with your computer or version of hoot, not sure. It is an emulator after all and isn't perfect. Can't say I've had that issue but maybe I have and just didn't notice it. 

Also a side note, since I started using hoot shuffle I've noticed that there's a lot of tracks that are either dead silence like the "Skip Song" tracks or ones that are sound effects that last a few seconds. I've also heard some rare tracks that are some sort of sound effect that loops, like a crowd cheering. Those can be annoying to listen to for 3 minutes straight which is actually why I kept the ability to manually shuffle so you can skip them. It might be a good idea to write down the names of those types of tracks and remove them maybe. Anything that doesn't really make sense for a shuffle playlist should probably get pruned but up to you since you own this repo.

**Comment by czarek7711** [comment]
> By previous pull do you mean the first one I did? Or the newest one?

This is pull nr 2, so by previous one I mean pull nr 1. I haven't tried out changes from this pull yet.

> This will happen if you press the manual shuffle button more than once.

Then that's not the case here, I'm pressing the key only once. I've noticed that when this issue happens, there is information logged in console about no audio being played for 5 seconds, even though some track is being played.

> That might be an issue with your computer or version of hoot, not sure. It is an emulator after all and isn't perfect. Can't say I've had that issue but maybe I have and just didn't notice it.

A similar issue I had today - a track starts playing, and after a fraction of a second, maybe 1/4s, it stops and another track plays instead immediately.

Of course if solution for any issue leaves doors open for any malicious actions then it can't be considered a solution.

> Also a side note, since I started using hoot shuffle I've noticed that there's a lot of tracks that are either dead silence like the "Skip Song" tracks or ones that are sound effects that last a few seconds.

The "Stop song" tracks do have a purpose occasionally. For some soundtracks they allow to stop a track with a fade-out. For others they can be used to stop a track without having to reload pcm data, which can be useful for soundtracks where loading pcm data is buggy.

There are a few sound effects which I'm actually quite fond of, but most of them probably aren't needed. That's something I can take care of when I have a bit of free time. I've never used hoot for playing background music, so it's never been an issue. I've also noticed volume balancing between games needs work. If I end up using hoot shuffle more I may try to dedicate some time for it. It will never be perfect so I'd probably focus only on clear outliers.

**Comment by Shadowdevo** [comment]
So I've been using the most recent version of hoot shuffle and everything seems to be working properly for the most part. I think I experienced a stutter/repeat maybe once or twice in a span of about 3 hours. I think that's just a hoot thing if songs are selected quickly which I might be able to fix by increasing the sleeps in the AHK script between actions. I'll test that soon and let you know if that fixes it. If not, then it's probably something to do with loading different sound engines and would be a hoot issue. 

Here's a vod of a stream I did earlier while using it if you're interested to compare how it works for you versus me: https://www.twitch.tv/videos/1057979399

**Comment by czarek7711** [comment]
Both issues are still present in the newest version for me. They do occur only occasionally though. I'm pretty sure what happens with the repeat/stutter one is: hoot shuffle picks a game, and while scrolling to pick a track it starts playing some other track from that game along the way.

The other issue may be connected to how you check for no audio playing. Maybe it's something to do with sound drivers, hard to say. But when I tested it today, it picked a game with only one song added, played it for a few seconds and then picked a new track on its own, while logging information about no audio being played for 5 seconds.

It would be great if you could look into these issues some more. If you can't figure out anything then I'll merge this request as it at least doesn't make them worse.

**Comment by Shadowdevo** [comment]
> I'm pretty sure what happens with the repeat/stutter one is: hoot shuffle picks a game, and while scrolling to pick a track it starts playing some other track from that game along the way.

You are totally right! When I wrote the AHK script I made an error while selecting a track. It flips a coin to see if it should continue indexing through songs but it presses enter (selects a track) before every flip. I'll get this fixed right now and push the change. 

For problem of tracks getting skipped when audio is playing, that is a harder one to figure out. I'll come up with a debugging executable and create a new branch on my fork called **debug**. It will have verbose output so you can see what exactly is going on when something like that happens.

**Comment by czarek7711** [comment]
I can confirm the repeat/stutter issue is fixed. Thanks!

**Pull request merged**
